version: '3.8'

services:
  chatbot:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_MODEL=gpt-3.5-turbo
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - GEMINI_MODEL=gemini-1.5-flash
      - MAX_CONVERSATION_HISTORY=10
      - ESCALATION_KEYWORDS=urgent,emergency,complaint,supervisor,manager,cancel,refund
      - SESSION_TIMEOUT=1800000
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  redis_data:
